import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Menu, BookOpen, Code, Database, Server, Check, Copy } from "lucide-react";
import { Sidebar } from "@/components/Sidebar";

export const Route = createFileRoute("/documentation")({
  component: DocumentationPage,
});

const endpoints = [
  {
    method: "POST",
    path: "/api/v1/auth/login",
    desc: "Authenticates a user and returns a JWT token.",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
  },
  {
    method: "GET",
    path: "/api/v1/users/profile",
    desc: "Retrieves the profile of the currently authenticated user.",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
  },
  {
    method: "PUT",
    path: "/api/v1/settings",
    desc: "Updates application settings for the tenant.",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
  },
  {
    method: "DELETE",
    path: "/api/v1/sessions/:id",
    desc: "Revokes a specific active session.",
    color: "text-fuchsia-400",
    bg: "bg-fuchsia-500/10",
  }
];

function DocumentationPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const copyCode = () => {
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <main className="min-h-screen bg-background text-foreground flex">
      <div className="absolute inset-0 noise pointer-events-none" />
      <Sidebar mobileOpen={menuOpen} onClose={() => setMenuOpen(false)} />

      <div className="relative z-10 flex-1 min-w-0 overflow-y-auto p-5 md:p-10">
        <header className="max-w-7xl mx-auto flex flex-col md:flex-row md:items-end justify-between gap-5 mb-8">
          <div>
            <button
              onClick={() => setMenuOpen(true)}
              className="md:hidden mb-5 grid size-11 place-items-center rounded-xl border border-border bg-white/5"
              aria-label="Open navigation"
            >
              <Menu className="size-5" />
            </button>
            <p className="text-xs uppercase tracking-[0.24em] text-fuchsia-300 mb-2">
              Auto-Generated By Documentation Agent
            </p>
            <h1 className="font-display text-4xl md:text-5xl">API Reference</h1>
            <p className="text-muted-foreground mt-2 max-w-2xl">
              Always up-to-date documentation generated directly from your codebase's AST and inline comments.
            </p>
          </div>
        </header>

        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-6">
            {endpoints.map((ep, idx) => (
              <div key={idx} className="glass rounded-3xl p-6 border border-white/10 hover:bg-white/5 transition-colors">
                <div className="flex items-center gap-4 mb-4">
                  <span className={`font-mono text-sm font-bold px-3 py-1 rounded-full ${ep.bg} ${ep.color}`}>
                    {ep.method}
                  </span>
                  <span className="font-mono text-lg">{ep.path}</span>
                </div>
                <p className="text-muted-foreground">{ep.desc}</p>
                
                {idx === 0 && (
                  <div className="mt-6 rounded-xl border border-white/10 bg-black/40 overflow-hidden">
                    <div className="flex items-center justify-between px-4 py-2 bg-white/5 border-b border-white/10">
                      <span className="text-xs font-mono text-muted-foreground">Response Example (200 OK)</span>
                      <button onClick={copyCode} className="text-muted-foreground hover:text-foreground transition-colors">
                        {copied ? <Check className="size-4 text-emerald-400" /> : <Copy className="size-4" />}
                      </button>
                    </div>
                    <div className="p-4 overflow-x-auto">
                      <pre className="text-sm font-mono leading-relaxed">
                        <span className="text-fuchsia-300">{"{"}</span>{"\n"}
                        <span className="text-cyan-300">  "token"</span>: <span className="text-emerald-300">"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."</span>,{"\n"}
                        <span className="text-cyan-300">  "user"</span>: {"{"}{"\n"}
                        <span className="text-cyan-300">    "id"</span>: <span className="text-emerald-300">"usr_12345"</span>,{"\n"}
                        <span className="text-cyan-300">    "email"</span>: <span className="text-emerald-300">"demo@example.com"</span>,{"\n"}
                        <span className="text-cyan-300">    "role"</span>: <span className="text-emerald-300">"admin"</span>{"\n"}
                        <span className="text-fuchsia-300">  {"}"}</span>{"\n"}
                        <span className="text-fuchsia-300">{"}"}</span>
                      </pre>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          <div className="space-y-6">
            <div className="glass rounded-3xl p-6 border border-fuchsia-500/20">
              <h3 className="font-display text-xl mb-4 flex items-center gap-2">
                <BookOpen className="size-5 text-fuchsia-300" />
                Live Sync Status
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">Last synchronized</span>
                  <span>2 mins ago</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">Files indexed</span>
                  <span>142</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">Stale docs detected</span>
                  <span className="text-emerald-400">0</span>
                </div>
              </div>
              <button className="w-full mt-6 py-2.5 bg-white/5 hover:bg-white/10 rounded-xl text-sm font-medium transition-colors border border-white/10">
                Force Re-index
              </button>
            </div>

            <div className="glass rounded-3xl p-6">
              <h3 className="font-display text-xl mb-4">Architecture</h3>
              <div className="space-y-3">
                <div className="flex items-center gap-3 text-sm p-3 rounded-xl bg-white/5 border border-white/10">
                  <Server className="size-4 text-cyan-300 shrink-0" />
                  <span>Node.js / Express</span>
                </div>
                <div className="flex items-center gap-3 text-sm p-3 rounded-xl bg-white/5 border border-white/10">
                  <Database className="size-4 text-blue-300 shrink-0" />
                  <span>PostgreSQL (Prisma)</span>
                </div>
                <div className="flex items-center gap-3 text-sm p-3 rounded-xl bg-white/5 border border-white/10">
                  <Code className="size-4 text-amber-300 shrink-0" />
                  <span>React / Vite</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
