/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as MissionsMissionIdRouteImport } from './routes/missions/$missionId'
import { Route as WorkspaceRepoIdRouteImport } from './routes/workspace/$repoId'
import { Route as WorkspaceRepoIdDebugRouteImport } from './routes/workspace/$repoId/debug'
import { Route as WorkspaceRepoIdDocsRouteImport } from './routes/workspace/$repoId/docs'
import { Route as WorkspaceRepoIdGraphRouteImport } from './routes/workspace/$repoId/graph'
import { Route as WorkspaceRepoIdTestingRouteImport } from './routes/workspace/$repoId/testing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsMissionIdRoute = MissionsMissionIdRouteImport.update({
  id: '/missions/$missionId',
  path: '/missions/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRepoIdRoute = WorkspaceRepoIdRouteImport.update({
  id: '/workspace/$repoId',
  path: '/workspace/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRepoIdDebugRoute = WorkspaceRepoIdDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => WorkspaceRepoIdRoute,
} as any)
const WorkspaceRepoIdDocsRoute = WorkspaceRepoIdDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => WorkspaceRepoIdRoute,
} as any)
const WorkspaceRepoIdGraphRoute = WorkspaceRepoIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => WorkspaceRepoIdRoute,
} as any)
const WorkspaceRepoIdTestingRoute = WorkspaceRepoIdTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => WorkspaceRepoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/documentation': typeof DocumentationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/repositories': typeof RepositoriesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/workspace/$repoId': typeof WorkspaceRepoIdRouteWithChildren
  '/workspace/$repoId/debug': typeof WorkspaceRepoIdDebugRoute
  '/workspace/$repoId/docs': typeof WorkspaceRepoIdDocsRoute
  '/workspace/$repoId/graph': typeof WorkspaceRepoIdGraphRoute
  '/workspace/$repoId/testing': typeof WorkspaceRepoIdTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/documentation': typeof DocumentationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/repositories': typeof RepositoriesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/workspace/$repoId': typeof WorkspaceRepoIdRouteWithChildren
  '/workspace/$repoId/debug': typeof WorkspaceRepoIdDebugRoute
  '/workspace/$repoId/docs': typeof WorkspaceRepoIdDocsRoute
  '/workspace/$repoId/graph': typeof WorkspaceRepoIdGraphRoute
  '/workspace/$repoId/testing': typeof WorkspaceRepoIdTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/documentation': typeof DocumentationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/repositories': typeof RepositoriesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/workspace/$repoId': typeof WorkspaceRepoIdRouteWithChildren
  '/workspace/$repoId/debug': typeof WorkspaceRepoIdDebugRoute
  '/workspace/$repoId/docs': typeof WorkspaceRepoIdDocsRoute
  '/workspace/$repoId/graph': typeof WorkspaceRepoIdGraphRoute
  '/workspace/$repoId/testing': typeof WorkspaceRepoIdTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/documentation'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/processing'
    | '/profile'
    | '/repositories'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/missions/$missionId'
    | '/workspace/$repoId'
    | '/workspace/$repoId/debug'
    | '/workspace/$repoId/docs'
    | '/workspace/$repoId/graph'
    | '/workspace/$repoId/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/documentation'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/processing'
    | '/profile'
    | '/repositories'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/missions/$missionId'
    | '/workspace/$repoId'
    | '/workspace/$repoId/debug'
    | '/workspace/$repoId/docs'
    | '/workspace/$repoId/graph'
    | '/workspace/$repoId/testing'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/documentation'
    | '/forgot-password'
    | '/import'
    | '/login'
    | '/processing'
    | '/profile'
    | '/repositories'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/missions/$missionId'
    | '/workspace/$repoId'
    | '/workspace/$repoId/debug'
    | '/workspace/$repoId/docs'
    | '/workspace/$repoId/graph'
    | '/workspace/$repoId/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  DocumentationRoute: typeof DocumentationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  ProcessingRoute: typeof ProcessingRoute
  ProfileRoute: typeof ProfileRoute
  RepositoriesRoute: typeof RepositoriesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  MissionsMissionIdRoute: typeof MissionsMissionIdRoute
  WorkspaceRepoIdRoute: typeof WorkspaceRepoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$missionId': {
      id: '/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof MissionsMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$repoId': {
      id: '/workspace/$repoId'
      path: '/workspace/$repoId'
      fullPath: '/workspace/$repoId'
      preLoaderRoute: typeof WorkspaceRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$repoId/debug': {
      id: '/workspace/$repoId/debug'
      path: '/debug'
      fullPath: '/workspace/$repoId/debug'
      preLoaderRoute: typeof WorkspaceRepoIdDebugRouteImport
      parentRoute: typeof WorkspaceRepoIdRoute
    }
    '/workspace/$repoId/docs': {
      id: '/workspace/$repoId/docs'
      path: '/docs'
      fullPath: '/workspace/$repoId/docs'
      preLoaderRoute: typeof WorkspaceRepoIdDocsRouteImport
      parentRoute: typeof WorkspaceRepoIdRoute
    }
    '/workspace/$repoId/graph': {
      id: '/workspace/$repoId/graph'
      path: '/graph'
      fullPath: '/workspace/$repoId/graph'
      preLoaderRoute: typeof WorkspaceRepoIdGraphRouteImport
      parentRoute: typeof WorkspaceRepoIdRoute
    }
    '/workspace/$repoId/testing': {
      id: '/workspace/$repoId/testing'
      path: '/testing'
      fullPath: '/workspace/$repoId/testing'
      preLoaderRoute: typeof WorkspaceRepoIdTestingRouteImport
      parentRoute: typeof WorkspaceRepoIdRoute
    }
  }
}

interface WorkspaceRepoIdRouteChildren {
  WorkspaceRepoIdDebugRoute: typeof WorkspaceRepoIdDebugRoute
  WorkspaceRepoIdDocsRoute: typeof WorkspaceRepoIdDocsRoute
  WorkspaceRepoIdGraphRoute: typeof WorkspaceRepoIdGraphRoute
  WorkspaceRepoIdTestingRoute: typeof WorkspaceRepoIdTestingRoute
}

const WorkspaceRepoIdRouteChildren: WorkspaceRepoIdRouteChildren = {
  WorkspaceRepoIdDebugRoute: WorkspaceRepoIdDebugRoute,
  WorkspaceRepoIdDocsRoute: WorkspaceRepoIdDocsRoute,
  WorkspaceRepoIdGraphRoute: WorkspaceRepoIdGraphRoute,
  WorkspaceRepoIdTestingRoute: WorkspaceRepoIdTestingRoute,
}

const WorkspaceRepoIdRouteWithChildren = WorkspaceRepoIdRoute._addFileChildren(
  WorkspaceRepoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  DocumentationRoute: DocumentationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  ProcessingRoute: ProcessingRoute,
  ProfileRoute: ProfileRoute,
  RepositoriesRoute: RepositoriesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  MissionsMissionIdRoute: MissionsMissionIdRoute,
  WorkspaceRepoIdRoute: WorkspaceRepoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
