/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as WorkspaceRepoIdRouteImport } from './routes/workspace/$repoId'
import { Route as WorkspaceRepoIdDebugRouteImport } from './routes/workspace/$repoId/debug'
import { Route as WorkspaceRepoIdDocsRouteImport } from './routes/workspace/$repoId/docs'
import { Route as WorkspaceRepoIdGraphRouteImport } from './routes/workspace/$repoId/graph'
import { Route as WorkspaceRepoIdTestingRouteImport } from './routes/workspace/$repoId/testing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRepoIdRoute = WorkspaceRepoIdRouteImport.update({
  id: '/workspace/$repoId',
  path: '/workspace/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRepoIdDebugRoute = WorkspaceRepoIdDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => WorkspaceRepoIdRoute,
} as any)
const WorkspaceRepoIdDocsRoute = WorkspaceRepoIdDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => WorkspaceRepoIdRoute,
} as any)
const WorkspaceRepoIdGraphRoute = WorkspaceRepoIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => WorkspaceRepoIdRoute,
} as any)
const WorkspaceRepoIdTestingRoute = WorkspaceRepoIdTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => WorkspaceRepoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/processing': typeof ProcessingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$repoId': typeof WorkspaceRepoIdRouteWithChildren
  '/workspace/$repoId/debug': typeof WorkspaceRepoIdDebugRoute
  '/workspace/$repoId/docs': typeof WorkspaceRepoIdDocsRoute
  '/workspace/$repoId/graph': typeof WorkspaceRepoIdGraphRoute
  '/workspace/$repoId/testing': typeof WorkspaceRepoIdTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/processing': typeof ProcessingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$repoId': typeof WorkspaceRepoIdRouteWithChildren
  '/workspace/$repoId/debug': typeof WorkspaceRepoIdDebugRoute
  '/workspace/$repoId/docs': typeof WorkspaceRepoIdDocsRoute
  '/workspace/$repoId/graph': typeof WorkspaceRepoIdGraphRoute
  '/workspace/$repoId/testing': typeof WorkspaceRepoIdTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/processing': typeof ProcessingRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/workspace/$repoId': typeof WorkspaceRepoIdRouteWithChildren
  '/workspace/$repoId/debug': typeof WorkspaceRepoIdDebugRoute
  '/workspace/$repoId/docs': typeof WorkspaceRepoIdDocsRoute
  '/workspace/$repoId/graph': typeof WorkspaceRepoIdGraphRoute
  '/workspace/$repoId/testing': typeof WorkspaceRepoIdTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/import'
    | '/processing'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$repoId'
    | '/workspace/$repoId/debug'
    | '/workspace/$repoId/docs'
    | '/workspace/$repoId/graph'
    | '/workspace/$repoId/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/import'
    | '/processing'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$repoId'
    | '/workspace/$repoId/debug'
    | '/workspace/$repoId/docs'
    | '/workspace/$repoId/graph'
    | '/workspace/$repoId/testing'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/import'
    | '/processing'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/workspace/$repoId'
    | '/workspace/$repoId/debug'
    | '/workspace/$repoId/docs'
    | '/workspace/$repoId/graph'
    | '/workspace/$repoId/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  ProcessingRoute: typeof ProcessingRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  WorkspaceRepoIdRoute: typeof WorkspaceRepoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$repoId': {
      id: '/workspace/$repoId'
      path: '/workspace/$repoId'
      fullPath: '/workspace/$repoId'
      preLoaderRoute: typeof WorkspaceRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$repoId/debug': {
      id: '/workspace/$repoId/debug'
      path: '/debug'
      fullPath: '/workspace/$repoId/debug'
      preLoaderRoute: typeof WorkspaceRepoIdDebugRouteImport
      parentRoute: typeof WorkspaceRepoIdRoute
    }
    '/workspace/$repoId/docs': {
      id: '/workspace/$repoId/docs'
      path: '/docs'
      fullPath: '/workspace/$repoId/docs'
      preLoaderRoute: typeof WorkspaceRepoIdDocsRouteImport
      parentRoute: typeof WorkspaceRepoIdRoute
    }
    '/workspace/$repoId/graph': {
      id: '/workspace/$repoId/graph'
      path: '/graph'
      fullPath: '/workspace/$repoId/graph'
      preLoaderRoute: typeof WorkspaceRepoIdGraphRouteImport
      parentRoute: typeof WorkspaceRepoIdRoute
    }
    '/workspace/$repoId/testing': {
      id: '/workspace/$repoId/testing'
      path: '/testing'
      fullPath: '/workspace/$repoId/testing'
      preLoaderRoute: typeof WorkspaceRepoIdTestingRouteImport
      parentRoute: typeof WorkspaceRepoIdRoute
    }
  }
}

interface WorkspaceRepoIdRouteChildren {
  WorkspaceRepoIdDebugRoute: typeof WorkspaceRepoIdDebugRoute
  WorkspaceRepoIdDocsRoute: typeof WorkspaceRepoIdDocsRoute
  WorkspaceRepoIdGraphRoute: typeof WorkspaceRepoIdGraphRoute
  WorkspaceRepoIdTestingRoute: typeof WorkspaceRepoIdTestingRoute
}

const WorkspaceRepoIdRouteChildren: WorkspaceRepoIdRouteChildren = {
  WorkspaceRepoIdDebugRoute: WorkspaceRepoIdDebugRoute,
  WorkspaceRepoIdDocsRoute: WorkspaceRepoIdDocsRoute,
  WorkspaceRepoIdGraphRoute: WorkspaceRepoIdGraphRoute,
  WorkspaceRepoIdTestingRoute: WorkspaceRepoIdTestingRoute,
}

const WorkspaceRepoIdRouteWithChildren = WorkspaceRepoIdRoute._addFileChildren(
  WorkspaceRepoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  ProcessingRoute: ProcessingRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  WorkspaceRepoIdRoute: WorkspaceRepoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
